2018-05-31 17:48:18,133 - router.router_app - INFO - Starting Router...
2018-05-31 17:48:18,142 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 17:48:18,143 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 17:48:18,145 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 17:48:18,165 - router.router_app - INFO - Starting Router...
2018-05-31 17:48:18,174 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 17:48:18,175 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 17:48:18,178 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 17:48:26,702 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:48:26,706 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:26,708 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:26,710 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:26,711 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:26,712 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:26,714 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:53,998 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:48:54,002 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:54,003 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:54,005 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:54,006 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:54,007 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:48:54,008 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:50:01,375 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:50:01,380 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:50:01,381 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:50:01,383 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:50:01,384 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:50:01,386 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:50:01,387 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:06,710 - router.router_app - INFO - Starting Router...
2018-05-31 17:57:06,720 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 17:57:06,721 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 17:57:06,726 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 17:57:06,745 - router.router_app - INFO - Starting Router...
2018-05-31 17:57:06,755 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 17:57:06,756 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 17:57:06,759 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 17:57:23,195 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:23,198 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:23,200 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:23,202 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:23,203 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:23,205 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:23,206 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:25,500 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:25,503 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:25,505 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:25,506 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:25,508 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:25,509 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:25,510 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:27,547 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:27,553 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:27,556 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:27,557 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:27,559 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:27,561 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:27,563 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:30,076 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:30,080 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:30,081 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:30,082 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:30,084 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:30,086 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:30,087 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:32,058 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:32,062 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:32,064 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:32,065 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:32,066 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:32,068 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:32,069 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:33,922 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:33,928 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:33,930 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:33,932 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:33,934 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:33,936 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:33,937 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:35,602 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 17:57:35,606 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:35,607 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:35,609 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:35,611 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:35,612 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 17:57:35,614 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:30:37,128 - router.router_app - INFO - Starting Router...
2018-05-31 18:30:37,137 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:30:37,138 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:30:38,235 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:30:38,298 - router.router_app - INFO - Starting Router...
2018-05-31 18:30:38,326 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:30:38,327 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:30:38,333 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:30:52,664 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:30:52,678 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:30:52,681 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:30:52,683 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:30:52,697 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:30:52,705 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:30:52,707 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:32:41,786 - router.router_app - INFO - Starting Router...
2018-05-31 18:32:41,796 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:32:41,797 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:32:41,800 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:32:41,817 - router.router_app - INFO - Starting Router...
2018-05-31 18:32:41,825 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:32:41,826 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:32:41,828 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:33:51,389 - router.router_app - INFO - Starting Router...
2018-05-31 18:33:51,399 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:33:51,400 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:33:51,403 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:33:51,421 - router.router_app - INFO - Starting Router...
2018-05-31 18:33:51,430 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:33:51,431 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:33:51,436 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:34:31,989 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:34:31,992 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:34:31,994 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:34:31,995 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:34:31,996 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:34:31,998 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:34:31,999 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:35:00,680 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:35:00,683 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:35:00,685 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:35:00,687 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:35:00,689 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:35:00,691 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:35:00,693 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:37:59,859 - router.router_app - INFO - Starting Router...
2018-05-31 18:37:59,869 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:37:59,869 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:37:59,872 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:37:59,890 - router.router_app - INFO - Starting Router...
2018-05-31 18:37:59,900 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:37:59,901 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:37:59,904 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:38:04,358 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:38:04,361 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:04,364 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:04,366 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:04,367 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:04,369 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:04,371 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:26,298 - router.router_app - INFO - Starting Router...
2018-05-31 18:38:26,308 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:38:26,308 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:38:26,311 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:38:26,329 - router.router_app - INFO - Starting Router...
2018-05-31 18:38:26,339 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:38:26,340 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:38:26,343 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:38:30,947 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:38:30,950 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:30,953 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:30,954 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:30,956 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:30,957 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:30,958 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:58,450 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:38:58,453 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:58,454 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:58,456 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:58,457 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:58,458 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:38:58,460 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:49:53,699 - router.router_app - INFO - Starting Router...
2018-05-31 18:49:53,709 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:49:53,710 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:49:53,713 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:49:53,730 - router.router_app - INFO - Starting Router...
2018-05-31 18:49:53,740 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:49:53,740 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:49:53,743 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:50:08,029 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:50:08,032 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:08,034 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:08,035 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:08,036 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:08,038 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:08,040 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:10,310 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:50:10,313 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:10,314 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:10,316 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:10,318 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:10,319 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:10,321 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:12,031 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:50:12,034 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:12,035 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:12,037 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:12,039 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:12,040 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:12,042 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:13,788 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:50:13,791 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:13,792 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:13,793 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:13,794 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:13,796 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:13,797 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:15,415 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:50:15,420 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:15,424 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:15,429 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:15,433 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:15,435 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:15,437 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:16,935 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:50:16,940 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:16,943 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:16,946 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:16,950 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:16,953 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:50:16,955 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:51:50,700 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:52:15,205 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:52:15,209 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:52:15,212 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:52:15,213 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:52:15,214 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:52:15,216 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:52:15,217 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:55:05,101 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:55:05,104 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:55:05,105 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:55:05,106 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:55:05,108 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:55:05,110 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:55:05,111 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:59:00,603 - router.router_app - INFO - Starting Router...
2018-05-31 18:59:00,613 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:59:00,614 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:59:00,617 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:59:00,635 - router.router_app - INFO - Starting Router...
2018-05-31 18:59:00,645 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 18:59:00,645 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 18:59:00,648 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 18:59:18,240 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 18:59:18,244 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:59:18,246 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:59:18,248 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:59:18,250 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:59:18,251 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 18:59:18,252 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:02:06,337 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:03:50,955 - router.router_app - INFO - Starting Router...
2018-05-31 19:03:50,964 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:03:50,965 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:03:50,967 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:03:50,984 - router.router_app - INFO - Starting Router...
2018-05-31 19:03:50,994 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:03:50,995 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:03:50,998 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:03:56,125 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:04:54,001 - router.router_app - INFO - Starting Router...
2018-05-31 19:04:54,011 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:04:54,012 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:04:54,015 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:04:54,034 - router.router_app - INFO - Starting Router...
2018-05-31 19:04:54,043 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:04:54,044 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:04:54,047 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:04:57,517 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:04:57,520 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:04:57,522 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:04:57,523 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:04:57,525 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:04:57,526 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:04:57,528 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:06:43,792 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:06:43,795 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:06:43,797 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:06:43,799 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:06:43,801 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:06:43,802 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:06:43,804 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:19:14,527 - router.router_app - INFO - Starting Router...
2018-05-31 19:19:14,537 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:19:14,538 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:19:14,539 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:19:14,554 - router.router_app - INFO - Starting Router...
2018-05-31 19:19:14,563 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:19:14,563 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:19:14,565 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:21:09,993 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:21:09,996 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:21:09,998 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:21:09,999 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:21:10,000 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:21:10,001 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:21:10,002 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:11,136 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:25:11,139 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:11,140 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:11,142 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:11,143 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:11,144 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:11,146 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:29,801 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:25:29,804 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:29,806 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:29,807 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:29,808 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:29,810 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:25:29,812 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:29:57,535 - router.router_app - INFO - Starting Router...
2018-05-31 19:29:57,545 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:29:57,546 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:29:57,548 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:29:57,568 - router.router_app - INFO - Starting Router...
2018-05-31 19:29:57,578 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:29:57,579 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:29:57,581 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:30:03,203 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:30:03,207 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:30:03,208 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:30:03,209 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:30:03,211 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:30:03,213 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:30:03,214 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:31:41,146 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:31:41,148 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:31:41,149 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:31:41,151 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:31:41,152 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:31:41,154 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:31:41,156 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:33:49,980 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:33:49,982 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:33:49,983 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:33:49,985 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:33:49,987 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:33:49,988 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:33:49,989 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:34:35,439 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:34:35,441 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:34:35,442 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:34:35,444 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:34:35,446 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:34:35,447 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:34:35,449 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:37:36,053 - router.router_app - INFO - Starting Router...
2018-05-31 19:37:36,062 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:37:36,063 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:37:36,065 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:37:36,081 - router.router_app - INFO - Starting Router...
2018-05-31 19:37:36,090 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:37:36,090 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:37:36,092 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:37:40,033 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:37:40,036 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:37:40,038 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:37:40,039 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:37:40,040 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:37:40,041 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:37:40,043 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/Downloads/BigRLab_APIs/demoday_fs/web_lab/AIaas/AIaas/router/AI_worker_client.py", line 121, in predict
    prediction_output.result = client.predict(prediction_input)
AttributeError: 'NoneType' object has no attribute 'predict'
2018-05-31 19:42:59,298 - router.router_app - INFO - Starting Router...
2018-05-31 19:42:59,307 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:42:59,307 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:42:59,309 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:42:59,323 - router.router_app - INFO - Starting Router...
2018-05-31 19:42:59,330 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 19:42:59,331 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 19:42:59,333 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 19:43:03,519 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:43:03,535 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 19:43:03,578 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
2018-05-31 19:43:06,192 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:43:06,195 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 19:43:06,201 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
2018-05-31 19:43:07,609 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:43:07,613 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 19:43:07,619 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
2018-05-31 19:43:09,091 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:43:09,095 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 19:43:09,101 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
2018-05-31 19:44:34,641 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:44:34,645 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 19:44:34,651 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
2018-05-31 19:44:39,820 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 19:44:39,824 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 19:44:39,830 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
2018-05-31 20:09:30,730 - router.router_app - INFO - Starting Router...
2018-05-31 20:09:30,738 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 20:09:30,739 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 20:09:30,741 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 20:09:30,756 - router.router_app - INFO - Starting Router...
2018-05-31 20:09:30,764 - AIaas.router.AI_worker_client - INFO - load balancer inited...
2018-05-31 20:09:30,765 - AIaas.router.AI_worker_client - INFO - AIWorkerClient Inited...
2018-05-31 20:09:30,767 - AIaas.router.predict - INFO - Predict Inited...
2018-05-31 20:09:37,102 - AIaas.router.AI_worker_client - INFO - AI predict has been called..
2018-05-31 20:09:37,137 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2018-05-31 20:09:37,162 - AIaas.router.AI_worker_client - ERROR - Predict has failed.. 
Traceback (most recent call last):
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/leepand/anaconda2/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/Users/leepand/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 35] Resource temporarily unavailable
